name: flutter_camera_processing
description: A new Flutter project.
version: 0.0.1+1
# homepage:
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  camera: ^0.9.6
  ffi: ^1.2.1
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  image: ^3.2.0
  path_provider: ^2.0.10
  share_plus: ^4.0.4

dev_dependencies:
  ffigen: ^5.0.0 # dart run ffigen
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.markosyan.flutter_camera_processing
        pluginClass: FlutterCameraProcessingPlugin
      ios:
        pluginClass: FlutterCameraProcessingPlugin

ffigen:
  name: GeneratedBindings
  description: Bindings to opencv and zxing.
  output: "lib/generated_bindings.dart"
  headers:
    entry-points:
      - "ios/Classes/src/native_opencv.h"
      - "ios/Classes/src/native_zxing.h"
  # functions:
  #   include:
  #     - 'opencvVersion'
  #     - 'opencvProcessStream'
  #     - 'zxingVersion'
  #     - 'zxingRead'
  #     - 'zxingEncode'
